# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
# Uses a more common 2-digit versioning in Jenkins plugins. Can be replaced by semver: $MAJOR.$MINOR.$PATCH
version-template: $MAJOR.$MINOR

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bugfix
  - title: 📝 Documentation updates
    label: documentation
  - title: 📦 Dependency updates
    label: dependencies
  - title: 🚦 Internal changes
    label: internal
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

template: |
  ## Changes
  $CHANGES

replacers:
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: '[JENKINS-$1](https://issues.jenkins-ci.org/browse/JENKINS-$1) - '
  - search: '/\[*INFRA-(\d+)\]*\s*-*\s*/g'
    replace: '[INFRA-$1](https://issues.jenkins-ci.org/browse/INFRA-$1) - '
  - search: '/\[*WEBSITE-(\d+)\]*\s*-*\s*/g'
    replace: '[WEBSITE-$1](https://issues.jenkins-ci.org/browse/WEBSITE-$1) - '
  # TODO(oleg_nenashev): Find a better way to reference issues
  - search: '/\[*SECURITY-(\d+)\]*\s*-*\s*/g'
    replace: '[SECURITY-$1](https://jenkins.io/security/advisories/) - '
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: 'JFR'
    replace: 'Jenkinsfile Runner'
  - search: 'CWP'
    replace: 'Custom WAR Packager'
 
